Repository ChrisTitusTech/linutil, pull requests merged in 2024-09, with the labels that each got.

#241 Close linutil on Control-C, don't reset cursor position on exit
  tui/src/float.rs
  tui/src/main.rs
  tui/src/state.rs
Labels: bug

#304 fix: Correctly Detect Pictures Directory and Clone Path for Background
  tabs/applications-setup/dwmtitus-setup.sh
Labels: bug

#379 fix typos
  tui/src/hint.rs
  tui/src/state.rs
Labels: bug, refactor

#422 refactor: apt-get with nala and hardcoded package managers
  tabs/applications-setup/alacritty-setup.sh
  tabs/applications-setup/fastfetch-setup.sh
  tabs/applications-setup/kitty-setup.sh
  tabs/common-script.sh
  tabs/security/firewall-baselines.sh
  tabs/system-setup/1-compile-setup.sh
  tabs/system-setup/3-global-theme.sh
  tabs/system-setup/4-remove-snaps.sh
  tabs/system-setup/arch/paru-setup.sh
  tabs/system-setup/arch/yay-setup.sh
  tabs/system-setup/fedora/rpm-fusion-setup.sh
  tabs/system-setup/system-update.sh
  tabs/utils/bluetooth-control.sh
  tabs/utils/monitor-control/utility_functions.sh
  tabs/utils/numlock.sh
  tabs/utils/wifi-control.sh
Labels: refactor

#456 Fix wifi-manager
  tabs/utils/wifi-control.sh
Labels: bug

#462 Remove bashisms out of bluetooth-control
  tabs/utils/bluetooth-control.sh
Labels: bug

#436 Add git as a dependency for scripts that use it
  tabs/applications-setup/dwmtitus-setup.sh
  tabs/applications-setup/mybash-setup.sh
  tabs/applications-setup/neovim-setup.sh
Labels: bug, enhancement, refactor, UI/UX

#425 feat: Implement minimum TUI size
  tui/src/state.rs
Labels: UI/UX improvement

#469 Crated a GitHub Workflow that checks for bashisms
  .github/workflows/bashisms.yml
Labels: enhancement

#380 Refactor `gaming-setup.sh`
  tabs/system-setup/2-gaming-setup.sh
Labels: refactor

#459 Add checklists to issue templates & fix the formatting
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#461 Fix a typo & grammar in pull request template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#451 Add code understanding & testing point to Contributing Guidelines
  .github/CONTRIBUTING.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#478 System Cleanup
  tabs/system-setup/system-cleanup.sh
  tabs/system-setup/tab_data.toml
Labels: enhancement

#482 Replace echos with printf (common-script)
  tabs/common-script.sh
Labels: bug

#487 Update preview
  docs/assets/preview.png
Labels: enhancement

#395 Added Virtualization Setup for Fedora
  tabs/system-setup/fedora/virtualization.sh
  tabs/system-setup/tab_data.toml
Labels: enhancement

#394 refactor: command_exists
  tabs/common-script.sh
Labels: bug

#393 feat: Add User Manager
  docs/userguide.md
  tabs/utils/tab_data.toml
  tabs/utils/user-account-manager/add_to_group.sh
  tabs/utils/user-account-manager/add_user.sh
  tabs/utils/user-account-manager/change_password.sh
  tabs/utils/user-account-manager/delete_user.sh
  tabs/utils/user-account-manager/remove_from_group.sh
  tabs/utils/user-account-manager/utility_functions.sh
Labels: enhancement

#387 fix: Fixup preview rendering and logic of preview key binding being shown in shortcut list
  tui/src/floating_text.rs
  tui/src/hint.rs
Labels: bug

#347 refactor: Tab key
  tui/src/hint.rs
  tui/src/state.rs
Labels: refactor

#531 D2r posix update
  tabs/gaming/diablo-ii/d2r-loot-filters.sh
Labels: bug

#490 Refactor various components of Rust code
  tui/src/float.rs
  tui/src/hint.rs
  tui/src/state.rs
Labels: enhancement

#552 Added crates.io badge to the README
  README.md
Labels: documentation

#614 remove unnecessary packagers
  core/tabs/applications-setup/browser-setup.sh
  core/tabs/applications-setup/setup-flatpak.sh
  core/tabs/common-script.sh
  core/tabs/system-setup/docker-setup.sh
  core/tabs/system-setup/system-update.sh
Labels: bug

#616 use packager instead of dpkg
  core/tabs/applications-setup/browser-setup.sh
  core/tabs/applications-setup/fastfetch-setup.sh
  core/tabs/applications-setup/office-suite-setup.sh
Labels: bug

#617 ci: Add issue labeling & fix perms
  .github/workflows/issue-slash-commands.yaml
Labels: github actions

#619 Doc: Update README.md
  README.md
Labels: documentation

#573 Move scripts around & refactor existing ones
  core/tabs/applications-setup/browser-setup.sh
  core/tabs/applications-setup/docker-setup.sh
  core/tabs/applications-setup/grub-theme.sh
  core/tabs/applications-setup/linutil-installer.sh
  core/tabs/applications-setup/office-suite-setup.sh
  core/tabs/applications-setup/setup-flatpak.sh
  core/tabs/applications-setup/tab_data.toml
  core/tabs/system-setup/system-cleanup.sh
  core/tabs/system-setup/tab_data.toml
  core/tabs/utils/auto-mount.sh
  core/tabs/utils/samba-ssh-setup.sh
  core/tabs/utils/tab_data.toml
Labels: bug

#625 add missing task lists
  core/tabs/applications-setup/tab_data.toml
Labels: bug
