Repository ChrisTitusTech/linutil, pull requests merged in 2024-11, with the labels that each got.

#894 fix: aarch64 release
  .github/workflows/linutil.yml
Labels: github_actions

#896 fix(ci): shellcheck errors
  .github/workflows/shellcheck.yml
  .shellcheckrc
Labels: github_actions

#897 fix: Unnecessary arch update
  core/tabs/utils/encrypt_decrypt_tool.sh
Labels: bug

#793 refact(ci): bashisms.yml
  .github/workflows/bashisms.yml
Labels: github_actions

#705 refact fix: Flatpak
  core/tabs/applications-setup/Developer-tools/meld-setup.sh
  core/tabs/applications-setup/bottles-setup.sh
  core/tabs/applications-setup/communication-apps/slack-setup.sh
  core/tabs/applications-setup/communication-apps/zoom-setup.sh
  core/tabs/applications-setup/office-suites/libreoffice.sh
  core/tabs/applications-setup/office-suites/onlyoffice.sh
  core/tabs/applications-setup/office-suites/wpsoffice.sh
  core/tabs/applications-setup/setup-flatpak.sh
  core/tabs/common-script.sh
Labels: refactor

#901 refact(ci): Preview workflow to create PR
  .github/workflows/linutil.yml
  .github/workflows/preview.yml
Labels: github_actions

#893 feat: jetbrains-toolbox
  core/tabs/applications-setup/Developer-tools/jetbrains-toolbox.sh
  core/tabs/applications-setup/tab_data.toml
  core/tabs/common-script.sh
  docs/userguide.md
Labels: enhancement

#767 implement fish like tab completion
  tui/src/filter.rs
Labels: UI/UX

#761 chore: Add missing gaming deps
  core/tabs/system-setup/gaming-setup.sh
Labels: script

#831 Add greeter install for lightdm during dwm-titus setup
  core/tabs/applications-setup/dwmtitus-setup.sh
Labels: bug

#719 refact: multi-selection to per cmd
  core/src/inner.rs
  core/src/lib.rs
  core/tabs/system-setup/tab_data.toml
  core/tabs/utils/tab_data.toml
  tui/src/state.rs
  tui/src/theme.rs
Labels: refactor

#916 fix: flatpak path
  core/tabs/common-script.sh
Labels: bug

#755 implement word wrapping functionality
  Cargo.lock
  core/tabs/applications-setup/tab_data.toml
  core/tabs/gaming/tab_data.toml
  core/tabs/security/tab_data.toml
  core/tabs/system-setup/tab_data.toml
  docs/userguide.md
  tui/Cargo.toml
  tui/src/floating_text.rs
  tui/src/state.rs
Labels: UI/UX

#920 🦀 feat(ux): add a minimum size bypass cli flag
  man/linutil.1
  tui/src/main.rs
  tui/src/state.rs
Labels: UI/UX

#823 fix (dwmtitus-setup): dm picking
  core/tabs/applications-setup/dwmtitus-setup.sh
Labels: bug

#918 Implement Rounded corners
  tui/src/confirmation.rs
  tui/src/filter.rs
  tui/src/floating_text.rs
  tui/src/running_command.rs
  tui/src/state.rs
Labels: UI/UX

#754 refact: Handle temporary directories entirely within core
  core/src/inner.rs
  core/src/lib.rs
  tui/src/state.rs
  xtask/src/docgen.rs
Labels: rust, refactor

#787 Added support for installing podman
  core/tabs/applications-setup/podman-compose-setup.sh
  core/tabs/applications-setup/podman-setup.sh
  core/tabs/applications-setup/tab_data.toml
  docs/userguide.md
Labels: enhancement

#789 feat: btrfs assistant & grub-btrfs
  core/tabs/system-setup/fedora/fedora-btrfs-assistant.sh
  core/tabs/system-setup/tab_data.toml
  docs/userguide.md
Labels: enhancement

#790 docs: Change numlock description
  core/tabs/utils/numlock.sh
  core/tabs/utils/tab_data.toml
  docs/userguide.md
Labels: documentation

#683 📃 feat: Linux Neptune (Valve's kernel for SteamDeck) installation
  core/tabs/system-setup/arch/linux-neptune.sh
  core/tabs/system-setup/tab_data.toml
  docs/userguide.md
  tui/src/state.rs
Labels: enhancement

#797 feat: Add arch nvidia installation script
  core/tabs/system-setup/arch/nvidia-drivers.sh
  core/tabs/system-setup/tab_data.toml
  docs/userguide.md
Labels: enhancement

#805 chore: Use crossterm bundled with ratatui
  Cargo.lock
  tui/Cargo.toml
  tui/src/confirmation.rs
  tui/src/filter.rs
  tui/src/float.rs
  tui/src/floating_text.rs
  tui/src/main.rs
  tui/src/running_command.rs
  tui/src/state.rs
Labels: rust, refactor

#806 Remove dependabot ignores
  .github/dependabot.yml
Labels: github_actions

#811 refactor: Re-export ego-tree dependency from linutil core
  Cargo.lock
  Cargo.toml
  core/Cargo.toml
  core/src/lib.rs
  tui/Cargo.toml
  tui/src/filter.rs
  tui/src/hint.rs
  tui/src/state.rs
Labels: rust, refactor

#813 feat: Add Arch virtualization setup script
  core/tabs/system-setup/arch/virtualization.sh
  core/tabs/system-setup/tab_data.toml
  docs/userguide.md
Labels: enhancement

#814 feat: Alpine linux support
  .shellcheckrc
  core/tabs/applications-setup/Developer-tools/meld-setup.sh
  core/tabs/applications-setup/Developer-tools/neovim-setup.sh
  core/tabs/applications-setup/Developer-tools/vscode-setup.sh
  core/tabs/applications-setup/Developer-tools/vscodium-setup.sh
  core/tabs/applications-setup/alacritty-setup.sh
  core/tabs/applications-setup/android-debloat.sh
  core/tabs/applications-setup/browsers/brave.sh
  core/tabs/applications-setup/browsers/chromium.sh
  core/tabs/applications-setup/browsers/firefox.sh
  core/tabs/applications-setup/browsers/librewolf.sh
  core/tabs/applications-setup/browsers/lynx.sh
  core/tabs/applications-setup/browsers/thorium.sh
  core/tabs/applications-setup/browsers/waterfox.sh
  core/tabs/applications-setup/communication-apps/discord-setup.sh
  core/tabs/applications-setup/communication-apps/jitsi-setup.sh
  core/tabs/applications-setup/communication-apps/signal-setup.sh
  core/tabs/applications-setup/communication-apps/telegram-setup.sh
  core/tabs/applications-setup/communication-apps/thunderbird-setup.sh
  core/tabs/applications-setup/docker-setup.sh
  core/tabs/applications-setup/fastfetch-setup.sh
  core/tabs/applications-setup/kitty-setup.sh
  core/tabs/applications-setup/linutil-installer.sh
  core/tabs/applications-setup/linutil-updater.sh
  core/tabs/applications-setup/mybash-setup.sh
  core/tabs/applications-setup/office-suites/libreoffice.sh
  core/tabs/applications-setup/pdf-suites/evince.sh
  core/tabs/applications-setup/pdf-suites/okular.sh
  core/tabs/applications-setup/rofi-setup.sh
  core/tabs/applications-setup/zsh-setup.sh
  core/tabs/common-script.sh
  core/tabs/common-service-script.sh
  core/tabs/security/firewall-baselines.sh
  core/tabs/system-setup/compile-setup.sh
  core/tabs/system-setup/gaming-setup.sh
  core/tabs/system-setup/system-cleanup.sh
  core/tabs/system-setup/system-update.sh
  core/tabs/utils/bluetooth-control.sh
  core/tabs/utils/create-bootable-usb.sh
  core/tabs/utils/encrypt_decrypt_tool.sh
  core/tabs/utils/numlock.sh
  core/tabs/utils/ollama.sh
  core/tabs/utils/power-profile.sh
  core/tabs/utils/samba-ssh-setup.sh
  core/tabs/utils/timeshift.sh
  core/tabs/utils/utility_functions.sh
  core/tabs/utils/wifi-control.sh
Labels: enhancement

#815 fix: Ollama installation bug
  core/tabs/utils/ollama.sh
Labels: bug

#819 fix: starship instllation bug when using doas
  core/tabs/applications-setup/mybash-setup.sh
Labels: bug

#820 Add OpenSUSE to list of linutil added to package managers
  README.md
  core/tabs/applications-setup/linutil-installer.sh
Labels: enhancement

#824 Add required dependencies for dwm-titus on Arch
  core/tabs/applications-setup/dwmtitus-setup.sh
Labels: bug, script

#830 Increase scroll length
  tui/src/running_command.rs
Labels: UI/UX

#834 feat: Add `--skip-confirmation` flag
  man/linutil.1
  tui/src/main.rs
  tui/src/state.rs
Labels: UI/UX

#835 Linutil arguments when using `curl`
  README.md
  start.sh
  startdev.sh
Labels: documentation

#837 feat: printer driver installation
  core/tabs/utils/printers/install-cups.sh
  core/tabs/utils/printers/install-epson-printer-drivers.sh
  core/tabs/utils/tab_data.toml
  docs/userguide.md
Labels: enhancement

#838 feat: whatsapp desktop app
  core/tabs/applications-setup/communication-apps/zapzap-setup.sh
  core/tabs/applications-setup/tab_data.toml
Labels: enhancement

#842 feat: tor browser installation
  core/tabs/applications-setup/browsers/tor-browser.sh
  core/tabs/applications-setup/tab_data.toml
  docs/userguide.md
Labels: enhancement

#843 refact: system-update.sh
  core/tabs/system-setup/system-update.sh
Labels: refactor

#859 fix: Debian && popos gaming deps
  core/tabs/system-setup/gaming-setup.sh
Labels: bug

#862 Delist Firewall setup on systems with Firewalld installed, such as fedora
  core/tabs/security/tab_data.toml
Labels: bug

#863 fix(fedora): multimedia setup
  core/tabs/system-setup/fedora/multimedia-codecs.sh
Labels: bug

#877 fix: Autocpu-freq script not detecting battery on laptops
  core/tabs/utils/power-profile.sh
Labels: bug

#882 fix(system-cleanup): failing with no orphan packages on arch
  core/tabs/system-setup/system-cleanup.sh
Labels: bug

#898 feat: Command execution log
  Cargo.lock
  docs/roadmap.md
  tui/Cargo.toml
  tui/src/running_command.rs
Labels: enhancement, rust

#888 docs: new repo
  .github/mkdocs.yml
  .github/preview.gif
  .github/workflows/github-pages.yml
  .github/workflows/preview.yml
  .github/workflows/xtask.yml
  README.md
  docs/KnownIssues.md
  docs/assets/favicon.png
  docs/assets/preview.tape
  docs/contributing.md
  docs/faq.md
  docs/index.md
  docs/roadmap.md
  docs/userguide.md
  overrides/main.html
Labels: documentation

#902 fix(create-bootable-usb.sh) confirmation prompt
  core/tabs/utils/create-bootable-usb.sh
Labels: bug

#905 fix (ci): preview workflow
  .github/workflows/preview.yml
Labels: github_actions

#907 fix(fedora): Recent syntax changes with DNF5
  core/tabs/applications-setup/Developer-tools/sublime-setup.sh
  core/tabs/applications-setup/browsers/brave.sh
  core/tabs/applications-setup/browsers/vivaldi.sh
  core/tabs/applications-setup/docker-setup.sh
Labels: bug

#908 refact: auto-cpufreq
  core/tabs/applications-setup/auto-cpufreq.sh
  core/tabs/applications-setup/tab_data.toml
  core/tabs/utils/power-profile.sh
  core/tabs/utils/tab_data.toml
Labels: refactor

#910 Add aarch64 support for ngrok
  core/tabs/applications-setup/Developer-tools/ngrok-setup.sh
Labels: script

#912 fix: shfmt err
  .github/workflows/shellcheck.yml
Labels: bug, github_actions

#913 feat: Mouse scroll
  tui/src/confirmation.rs
  tui/src/float.rs
  tui/src/floating_text.rs
  tui/src/main.rs
  tui/src/running_command.rs
  tui/src/state.rs
Labels: enhancement, UI/UX

#915 refact: waydroid setup
  core/tabs/applications-setup/waydroid-setup.sh
Labels: bug, refactor

#922 Reduce linutil binary size by removing unused features from tui/Cargo.toml
  Cargo.lock
  tui/Cargo.toml
Labels: rust

#927 implement a root check menu
  Cargo.lock
  core/tabs/common-script.sh
  tui/Cargo.toml
  tui/src/main.rs
  tui/src/root.rs
  tui/src/state.rs
Labels: enhancement

#933 refact: rust fixes and optimizations
  Cargo.lock
  core/Cargo.toml
  core/src/config.rs
  core/src/inner.rs
  core/src/lib.rs
  tui/Cargo.toml
  tui/src/confirmation.rs
  tui/src/filter.rs
  tui/src/float.rs
  tui/src/floating_text.rs
  tui/src/hint.rs
  tui/src/main.rs
  tui/src/root.rs
  tui/src/running_command.rs
  tui/src/state.rs
  tui/src/theme.rs
  tui/src/tips.rs
Labels: rust, refactor

#964 docs(README): wrong crate name in `cargo install` instructions
  README.md
Labels: bug, documentation
