Repository ChrisTitusTech/linutil, pull requests merged in 2024-10, with the labels that each got.

#876 ⚙️ refact(release): better categories
  .github/release.yml
Labels: documentation

#828 feat: Drastically increase the operating system support for USB creation script
  core/tabs/utils/create-bootable-usb.sh
Labels: enhancement

#700 added waterfox browser
  core/tabs/applications-setup/browsers/waterfox.sh
  core/tabs/applications-setup/tab_data.toml
Labels: enhancement

#763 fix: bash deps
  core/tabs/applications-setup/mybash-setup.sh
Labels: bug

#762 make command_exists interpret multiple values
  core/tabs/common-script.sh
Labels: refactor

#883 ⚖️ docs: fix the security policy
  .github/SECURITY.md
Labels: documentation

#884 fix: github release notes not working
  .github/release.yml
Labels: bug, documentation

#881 🤖 fix(waydroid-setup): not installing `dkms` on arch
  core/tabs/applications-setup/waydroid-setup.sh
Labels: bug

#875 Update roadmap.md
  docs/roadmap.md
Labels: documentation

#878 Replace `BUILD_DATE` with `CARGO_PKG_VERSION`
  tui/Cargo.toml
  tui/build.rs
  tui/src/state.rs
Labels: rust

#723 fix color bleeding
  tui/src/floating_text.rs
Labels: UI/UX

#725 return user to their previous position if they exit a subdir
  tui/src/state.rs
Labels: UI/UX

#726 sort entries alphabetically
  core/tabs/applications-setup/tab_data.toml
Labels: UI/UX

#727 allow scrolling past last entry / first entry
  tui/src/state.rs
Labels: UI/UX

#729 dont allow scrolling when last line is visible
  tui/src/floating_text.rs
Labels: UI/UX

#733 fix: ssh commands
  core/tabs/utils/ssh.sh
Labels: bug

#747 fix issues with set brightness
  core/tabs/utils/monitor-control/set_brightness.sh
Labels: bug

#748 perf(paru-setup): use `-bin` packages for faster installation
  core/tabs/system-setup/arch/paru-setup.sh
Labels: refactor

#752 clear the search bar if the user changes categories
  tui/src/filter.rs
  tui/src/state.rs
Labels: UI/UX

#753 dont allow the user to bring up the command desc if there is none
  tui/src/state.rs
Labels: UI/UX

#758 do not exit linutil in confirmation prompt when q is pressed
  tui/src/confirmation.rs
  tui/src/state.rs
Labels: bug, UI/UX

#774 fix: fedora timeshift
  core/tabs/utils/tab_data.toml
Labels: bug

#886 feat(fedora): release upgrade script
  core/tabs/system-setup/fedora/fedora-upgrade.sh
  core/tabs/system-setup/tab_data.toml
Labels: enhancement

#697 fix(nala): remove autoclean from `system-cleanup.sh`
  core/tabs/system-setup/system-cleanup.sh
Labels: bug

#717 fix: Common script paths
  core/tabs/applications-setup/office-suites/freeoffice.sh
  core/tabs/applications-setup/office-suites/libreoffice.sh
  core/tabs/applications-setup/office-suites/onlyoffice.sh
  core/tabs/applications-setup/office-suites/wpsoffice.sh
  core/tabs/applications-setup/pdf-suites/evince.sh
  core/tabs/applications-setup/pdf-suites/okular.sh
  core/tabs/applications-setup/pdf-suites/pdfstudio.sh
  core/tabs/applications-setup/pdf-suites/pdfstudioviewer.sh
Labels: bug

#707 feat(docker-setup): fedora support
  core/tabs/applications-setup/docker-setup.sh
Labels: enhancement

#718 fix(browsers): vivaldi setup
  core/tabs/applications-setup/browsers/vivaldi.sh
Labels: bug

#728 fix: btrfs issue
  core/tabs/system-setup/arch/server-setup.sh
Labels: bug

#890 🖍️ feat(arch-setup): enable colors and the easter egg in `pacman`
  core/tabs/system-setup/arch/server-setup.sh
Labels: enhancement

#889 fix the repo
  Cargo.lock
  docs/userguide.md
Labels: bug

#792 ci: Seperate preview from Linutil Release
  .github/workflows/linutil.yml
  .github/workflows/preview.yml
Labels: github_actions

#791 ci: Remove unnecessary auto commit
  .github/workflows/linutil.yml
  docs/assets/preview.gif
Labels: github_actions

#892 fix: `ILoveCandy` in `pacman` conf
  core/tabs/system-setup/arch/server-setup.sh
Labels: bug

#865 chore: bump ratatui -> 0.29.0
  Cargo.lock
  tui/Cargo.toml
Labels: rust

#812 fix: Signal installation in fedora
  core/tabs/applications-setup/communication-apps/signal-setup.sh
Labels: bug
