Repository ChrisTitusTech/linutil, pull requests merged in 2025-01, with the labels that each got.

#988 chore: update copyright year
  LICENSE
  man/linutil.1
Labels: documentation

#971 refact: minor fixes
  tui/src/floating_text.rs
  tui/src/hint.rs
  tui/src/main.rs
  tui/src/state.rs
Labels: refactor

#991 chore(release): prepare for 25.1.10
  Cargo.lock
  Cargo.toml
  core/src/inner.rs
  tui/Cargo.toml
  tui/src/state.rs
Labels: rust
