Repository ChrisTitusTech/linutil, pull requests merged in 2025-02, with the labels that each got.

#995 chore: remove redundant files
  .github/requirements.txt
Labels: dependencies

#997 refact: fix (almost) all shellcheck errors
  core/tabs/applications-setup/android-debloat.sh
  core/tabs/applications-setup/browsers/librewolf.sh
  core/tabs/applications-setup/communication-apps/discord-setup.sh
  core/tabs/applications-setup/communication-apps/signal-setup.sh
  core/tabs/applications-setup/dwmtitus-setup.sh
  core/tabs/applications-setup/linutil-installer.sh
  core/tabs/applications-setup/linutil-updater.sh
  core/tabs/system-setup/compile-setup.sh
  core/tabs/system-setup/system-cleanup.sh
  core/tabs/utils/bluetooth-control.sh
  core/tabs/utils/encrypt_decrypt_tool.sh
  core/tabs/utils/monitor-control/set_brightness.sh
  core/tabs/utils/monitor-control/set_resolutions.sh
  core/tabs/utils/ollama.sh
  core/tabs/utils/samba-ssh-setup.sh
  core/tabs/utils/service-control.sh
  core/tabs/utils/timeshift.sh
  core/tabs/utils/user-account-manager/add_to_group.sh
  core/tabs/utils/user-account-manager/change_password.sh
  core/tabs/utils/user-account-manager/delete_user.sh
  core/tabs/utils/user-account-manager/remove_from_group.sh
  core/tabs/utils/utility_functions.sh
  core/tabs/utils/wifi-control.sh
Labels: refactor, script

#973 refactor(shortcuts): creation macro
  tui/src/confirmation.rs
  tui/src/floating_text.rs
  tui/src/hint.rs
  tui/src/running_command.rs
  tui/src/state.rs
Labels: refactor

#929 refact: categorize dev scripts & add zed editor installation
  core/tabs/applications-setup/developer-tools/githubdesktop.sh
  core/tabs/applications-setup/developer-tools/jetbrains-toolbox.sh
  core/tabs/applications-setup/developer-tools/meld.sh
  core/tabs/applications-setup/developer-tools/neovim.sh
  core/tabs/applications-setup/developer-tools/ngrok.sh
  core/tabs/applications-setup/developer-tools/sublime.sh
  core/tabs/applications-setup/developer-tools/vscode.sh
  core/tabs/applications-setup/developer-tools/vscodium.sh
  core/tabs/applications-setup/developer-tools/zed.sh
  core/tabs/applications-setup/tab_data.toml
Labels: enhancement, refactor

#979 fix(startdev): grep error
  startdev.sh
Labels: bug

#940 feat: Zen Browser installation
  core/tabs/applications-setup/browsers/zen-browser.sh
  core/tabs/applications-setup/tab_data.toml
Labels: enhancement

#1013 allow different os-releases and hyprland setup
  core/src/inner.rs
  core/tabs/system-setup/arch/hyprland-kool.sh
  core/tabs/system-setup/debian/hyprland-kool-deb.sh
  core/tabs/system-setup/fedora/hyprland-kool-fed.sh
  core/tabs/system-setup/tab_data.toml
  core/tabs/system-setup/ubuntu/hyprland-kool-ubuntu24.sh
Labels: enhancement, rust, refactor, script

#980 refact(brave-install): simplify script
  core/tabs/applications-setup/browsers/brave.sh
Labels: refactor

#1002 feat(fastfetch-setup): shell integration setup
  core/tabs/applications-setup/fastfetch-setup.sh
Labels: enhancement, script

#1003 ui: "unselect" the current tab when in search mode
  tui/src/state.rs
Labels: UI/UX

#1014 fix(zen-browser): remove redundant AVX2 check
  core/tabs/applications-setup/browsers/zen-browser.sh
Labels: bug, script

#1017 perf: increase rendering efficiency
  tui/src/main.rs
  tui/src/running_command.rs
Labels: rust, refactor

#1028 fix(compile-setup): dnf compile
  core/tabs/system-setup/compile-setup.sh
Labels: bug, script

#1032 fix(dwm-titus): Multiple fixes
  core/tabs/applications-setup/dwmtitus-setup.sh
Labels: bug, script
